controller_list:
  - name: fake_arm_controller
    type: interpolate
    joints:
      - base_rotation_joint
      - upper_arm_joint
      - forearm_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    type: interpolate
    joints:
      - gripper_left_joint
initial:
  - group: arm
    pose: home
  - group: gripper
    pose: home_gripper
