planner_configs:
  EST:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05
  LBKPIECE:
    type: geometric::LBKPIECE
    range: 0.0
    border_fraction: 0.9
    min_valid_path_fraction: 0.5
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  PRMstar:
    type: geometric::PRMstar
  BiTRRT:
    type: geometric::BiTRRT
    range: 0.0
    temp_change_factor: 0.1
    init_temperature: 100
    frountier_threshold: 0.0
    frountier_node_ratio: 0.1
    cost_threshold: 1e300
  PRM:
    type: geometric::PRM
    max_nearest_neighbors: 10
arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - EST
    - PRMstar
    - LBKPIECE
    - BiTRRT
  projection_evaluator: joints(base_rotation_joint,upper_arm_joint)
  longest_valid_segment_fraction: 0.005
gripper:
  planner_configs:
    - RRTConnect
    - EST
    - PRM
